In [ ]:
# !pip install numpy 패키지명  # pip(파이썬 인덱스 패키지)

In [2]:
!pwd

/content


In [3]:
!find / -name 'numpy*'

/usr/include/boost/python/numpy
/usr/include/boost/python/numpy/numpy_object_mgr_traits.hpp
/usr/include/boost/python/numpy.hpp
/usr/local/lib/python3.10/dist-packages/tensorflow/include/tsl/python/lib/core/numpy.h
/usr/local/lib/python3.10/dist-packages/tensorflow/include/external/pybind11/include/pybind11/numpy.h
/usr/local/lib/python3.10/dist-packages/tensorflow/include/external/pybind11/_virtual_includes/pybind11/pybind11/numpy.h
/usr/local/lib/python3.10/dist-packages/tensorflow/include/external/local_config_python/numpy_include
/usr/local/lib/python3.10/dist-packages/tensorflow/include/external/local_config_python/numpy_include/numpy
/usr/local/lib/python3.10/dist-packages/tensorflow/include/external/local_config_python/numpy_include/numpy/numpyconfig.h
/usr/local/lib/python3.10/dist-packages/tensorflow/include/tensorflow/tsl/python/lib/core/numpy.h
/usr/local/lib/python3.10/dist-packages/tensorflow/dtensor/python/numpy_util.py
/usr/local/lib/python3.10/dist-packages/tensorflow/d

In [1]:
import numpy

In [4]:
import numpy as np

In [7]:
# help(np.array)

In [ ]:
# np.array(1,2,3) # 오류남

In [35]:
arr1=np.array([1,2,3])  # 1차원은 리스트 1개로 사용 가능

In [36]:
# nd --> n차원(d = dimension = 차원)

In [37]:
type(arr1)

numpy.ndarray

In [38]:
arr1.shape

(3,)

In [39]:
arr1.size

3

In [40]:
arr1.ndim

1

In [41]:
arr2=np.array([[1,2,3],[4,5,6]])  # 2차원은 리스트 안에 리스트를 넣어라.

In [42]:
arr2.shape

(2, 3)

In [43]:
arr2.size

6

In [44]:
arr2.ndim

2

In [48]:
arr3=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])   # 3차원

In [49]:
arr3.ndim

3

In [51]:
arr3.shape  # (면, 행, 열)

(2, 2, 3)

In [52]:
arr3.size

12

In [54]:
arr4 = np.array([[1],
                [2],
                [-1.0],
                [3.14]])

In [55]:
arr4

array([[ 1.  ],
       [ 2.  ],
       [-1.  ],
       [ 3.14]])

In [57]:
arr4.shape

(4, 1)

In [58]:
arr4.ndim

2

In [66]:
arr4 = np.array([[[[1,2,-1,0,3.14]]]])

In [67]:
arr4

array([[[[ 1.  ,  2.  , -1.  ,  0.  ,  3.14]]]])

In [68]:
arr4.ndim

4

In [69]:
arr4.shape

(1, 1, 1, 5)

In [70]:
#  배열(넘파이 배열, np.array) 계산

In [71]:
mu = np.array([1,2,3])

In [73]:
nu = np.array([4,4,4])

In [75]:
mu + nu

array([5, 6, 7])

In [76]:
2 * (mu + nu)

array([10, 12, 14])

In [77]:
#  행렬의 연산

In [78]:
A = np.array([[3,6],[4,5]])

In [79]:
A

array([[3, 6],
       [4, 5]])

In [80]:
B = np.array([[5,8],[6,7]])

In [81]:
A + B

array([[ 8, 14],
       [10, 12]])

In [82]:
A - B

array([[-2, -2],
       [-2, -2]])

In [83]:
C = np.array([[5,8,9],[6,7,3]])

In [84]:
# A + C  # 오류남 # 차원 오류

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [85]:
np.all([True, True, True])

True

In [87]:
np.all([True, True, False])

False

In [88]:
np.any([False, False, False])

False

In [90]:
np.any([True, False, False])

True